import NavBar from "../components/NavBar";
import "./globals.css";
import { Rokkitt } from 'next/font/google';

export const metadata = {
  title: "uKnow",
  description: "Generated by create next app",
};

const rokkitt = Rokkitt({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={rokkitt.className}>
      <body>
        <NavBar />
        <div className="container mx-auto p-4">
          {children}
        </div>
      </body>
    </html>
  );
}
