import NavBar from "./components/NavBar";
import "./globals.css";

export const metadata = {
  title: "uKnow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <div className="container mx-auto p-4">
          {children}
        </div>
      </body>
    </html>
  );
}
